import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from './components/Header'
import Footer from './components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Alohana Cavaliers',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="min-h-screen">
      <body className={inter.className}>
        <Header/>
        <div className="bg-background background-height">
          <div className="container mx-auto"> 
            {children}
          </div>
        </div>
        <Footer/>
      </body>
    </html>
  )
}
