import type { Metadata } from 'next'
import { PT_Serif } from 'next/font/google'
import './globals.css'
import Header from './components/Header'
import Footer from './components/Footer'

const pt_serif = PT_Serif({ 
  subsets: ['latin'], 
  weight: ["400", "700"]
})

export const metadata: Metadata = {
  title: 'Alohana Cavaliers',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="min-h-screen">
      <body className={pt_serif.className}>
        <Header/>
        <div className="bg-background background-height">
          <div className="container mx-auto"> 
            {children}
          </div>
        </div>
        <Footer/>
      </body>
    </html>
  )
}
